## The below two functions are used to create a special matrix that will store its inverse in cache and then use the cache to return the inverse when x has not been reset.


## The output of the below function will be a list with four elements (set, get, setinverse, getinverse). 
##Each element is a function that will either set or get the values of x and i, which are the data elements for this environment."<<-" is being used to set/get the variable from parent environment.

makeCacheMatrix <- function(x = matrix()) {
							i <- NULL
								set <- function(y) {
										  x <<- y
										  i <<- NULL
								}
									get <- function() x
									setinverse <- function(solve) i <<- solve
									getinverse <- function() i
									list(set = set, get = get,
										 setinverse = setinverse,
										 getinverse = getinverse)

}


## The below function takes a list as input that has been generated by the makeCacheMatrix function. It will first check if the inverse value is cached. 
##If the values exists in cache, it will print out the message and get the values from cache. If not it will calcuate the inverse and will set the cache through $setinverse function.

cacheSolve <- function(x, ...) {
				i <- x$getinverse()
				  if(!is.null(i)) {
					message("getting cached data")
					return(i)
				  }
						  data <- x$get()
						  i <- solve(data, ...)
						  x$setinverse(i)
						  i
}
